# Generated by Django 4.0.3 on 2022-06-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=150)),
                ('userName', models.CharField(max_length=70, unique=True)),
                ('number', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=500)),
                ('profile_pic', models.ImageField(blank=True, default='default_img/nba.png', null=True, upload_to='profile_img/')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date-joined')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
