# Generated by Django 4.0.3 on 2022-06-28 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_number_account_number1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='number1',
            new_name='number',
        ),
    ]
