# Generated by Django 4.0.3 on 2022-06-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_number1_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
