# Generated by Django 4.0.3 on 2022-06-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otpveification1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, null=True)),
                ('otp', models.IntegerField(blank=True)),
            ],
        ),
    ]
