# Generated by Django 4.0.3 on 2022-06-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_otpveification1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpveification1',
            name='number',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
