# Generated by Django 4.0.3 on 2022-07-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_account_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_img/nba.png', null=True, upload_to='profile_img/'),
        ),
    ]
