# Generated by Django 4.0.3 on 2022-09-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_account_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_youtuber',
            field=models.BooleanField(default=False),
        ),
    ]
