# Generated by Django 4.0.3 on 2022-07-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='devicetoken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30, unique=True)),
                ('fcm_token', models.CharField(max_length=400)),
                ('messages', models.TextField(blank=True, default=[])),
            ],
        ),
    ]
