# Generated by Django 4.0.3 on 2022-07-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='log_status',
            field=models.BooleanField(default=False),
        ),
    ]
