# Generated by Django 4.0.3 on 2022-07-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebase', '0002_devicetoken_log_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='notificationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30)),
                ('messages', models.CharField(max_length=100)),
            ],
        ),
    ]
