# Generated by Django 4.0.3 on 2022-07-26 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firebase', '0003_notificationmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetoken',
            name='messages',
        ),
    ]
