# Generated by Django 4.0.3 on 2022-07-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebase', '0004_remove_devicetoken_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmessage',
            name='messages',
            field=models.CharField(max_length=250),
        ),
    ]
