# Generated by Django 4.0.3 on 2022-08-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebase', '0005_alter_notificationmessage_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='team_request',
            field=models.TextField(default=[]),
        ),
    ]
