# Generated by Django 4.0.3 on 2022-08-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebase', '0007_devicetoken_player_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='player_request',
            field=models.TextField(default={}),
        ),
    ]
