# Generated by Django 4.0.3 on 2022-07-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('userName', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=7)),
                ('height', models.CharField(max_length=10, null=True)),
                ('weight', models.CharField(max_length=5, null=True)),
                ('teams', models.TextField(default=[])),
                ('totalMatch', models.CharField(default={'Level 1': 0, 'Level 2': 0, 'Level 3': 0, 'Level 4': 0}, max_length=400)),
                ('points', models.CharField(default={'2attempt': 0, '2pm': 0, '3attempt': 0, '3pm': 0, 'F.T': 0, 'F.Tattempt': 0}, max_length=400)),
                ('assist', models.IntegerField(default=0)),
                ('block', models.IntegerField(default=0)),
                ('steal', models.IntegerField(default=0)),
                ('rebound', models.CharField(default={'Defensive': 0, 'Offensive': 0}, max_length=200)),
            ],
        ),
    ]
