# Generated by Django 4.0.3 on 2022-07-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=70)),
                ('team_pic', models.ImageField(blank=True, null=True, upload_to='team_img/')),
                ('owener', models.CharField(max_length=70)),
                ('players', models.TextField(default={})),
                ('tournement', models.TextField(default=[])),
                ('category', models.CharField(choices=[('3X3', '3x3'), ('5X5', '5X5')], default=('5X5', '5X5'), max_length=3)),
                ('address', models.CharField(max_length=200)),
                ('totalMatch', models.CharField(default={'Level 1': 0, 'Level 2': 0, 'Level 3': 0, 'Level 4': 0}, max_length=400)),
                ('points', models.CharField(default={'2attempt': 0, '2pm': 0, '3attempt': 0, '3pm': 0, 'F.T': 0, 'F.Tattempt': 0}, max_length=400)),
                ('assist', models.IntegerField(default=0)),
                ('block', models.IntegerField(default=0)),
                ('steal', models.IntegerField(default=0)),
                ('rebound', models.CharField(default={'Defensive': 0, 'Offensive': 0}, max_length=200)),
            ],
        ),
    ]
