# Generated by Django 4.0.3 on 2022-07-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_owener_team_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='pic',
            field=models.ImageField(null=True, upload_to='player_pic/'),
        ),
    ]
