# Generated by Django 4.0.3 on 2022-07-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_players_name_players_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
