# Generated by Django 4.0.3 on 2022-07-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_players_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='teams',
            field=models.CharField(default=[], max_length=300),
        ),
    ]
