# Generated by Django 4.0.3 on 2022-07-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_team_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='points',
            field=models.CharField(default={'2 attempt': 0, '2pm': 0, '3 attempt': 0, '3pm': 0, 'F.T': 0, 'F.T attempt': 0}, max_length=400),
        ),
    ]
