# Generated by Django 4.0.3 on 2022-08-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_players_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='teams',
            field=models.TextField(default=[]),
        ),
    ]
