# Generated by Django 4.0.3 on 2022-08-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_team_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tour_id', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('tour_name', models.CharField(max_length=200)),
                ('tour_category', models.CharField(choices=[('3X3', '3x3'), ('5X5', '5X5')], default=('5X5', '5X5'), max_length=3)),
                ('tour_venue', models.CharField(max_length=200)),
                ('tour_date', models.DateField()),
                ('tour_referee', models.TextField(blank=True)),
                ('tour_description', models.TextField(blank=True)),
            ],
        ),
    ]
