# Generated by Django 4.0.3 on 2022-08-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tour_owner',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
