# Generated by Django 4.0.3 on 2022-08-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_tournament_tour_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tour_teams',
            field=models.TextField(default=[]),
        ),
    ]
