# Generated by Django 4.0.3 on 2022-08-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_team_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tour_registration',
            field=models.BooleanField(default=True),
        ),
    ]
