# Generated by Django 4.0.3 on 2022-08-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_tournament_tour_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tour_fixture',
            field=models.ImageField(blank=True, null=True, upload_to='tour_fixtures/'),
        ),
    ]
