# Generated by Django 4.0.3 on 2022-08-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_tournament_tour_fixture'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='referee',
            field=models.TextField(default=[]),
        ),
    ]
