# Generated by Django 4.0.3 on 2022-08-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_players_referee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('tour_id', models.CharField(max_length=70)),
                ('match_between', models.CharField(default={}, max_length=300)),
                ('team_a_3', models.IntegerField()),
                ('team_a_3_attempt', models.IntegerField()),
                ('team_a_2', models.IntegerField()),
                ('team_a_2_attempt', models.IntegerField()),
                ('team_a_1', models.IntegerField()),
                ('team_a_1_attempt', models.IntegerField()),
                ('team_a_steal', models.IntegerField()),
                ('team_a_block', models.IntegerField()),
                ('team_a_assist', models.IntegerField()),
                ('team_a_offensive_rebound', models.IntegerField()),
                ('team_a_defensive_rebound', models.IntegerField()),
                ('team_a_player_stats', models.TextField(default={})),
                ('team_b_3', models.IntegerField()),
                ('team_b_3_attempt', models.IntegerField()),
                ('team_b_2', models.IntegerField()),
                ('team_b_2_attempt', models.IntegerField()),
                ('team_b_1', models.IntegerField()),
                ('team_b_1_attempt', models.IntegerField()),
                ('team_b_steal', models.IntegerField()),
                ('team_b_block', models.IntegerField()),
                ('team_b_assist', models.IntegerField()),
                ('team_b_offensive_rebound', models.IntegerField()),
                ('team_b_defensive_rebound', models.IntegerField()),
                ('team_b_player_stats', models.TextField(default={})),
            ],
        ),
    ]
