# Generated by Django 4.0.3 on 2022-08-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_alter_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='quarter',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
