# Generated by Django 4.0.3 on 2022-08-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_match_quarter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='quarter',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=('1', '1'), max_length=5),
        ),
    ]
