# Generated by Django 4.0.3 on 2022-09-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_alter_match_quarter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='quarter',
            field=models.CharField(default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(default='upcoming', max_length=10),
        ),
    ]
