# Generated by Django 4.0.3 on 2022-09-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_alter_match_quarter_alter_match_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRanking',
            fields=[
                ('userName', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('tour_id', models.CharField(max_length=70)),
                ('points', models.IntegerField(default=0)),
                ('rebound', models.IntegerField(default=0)),
                ('assist', models.IntegerField(default=0)),
                ('block', models.IntegerField(default=0)),
                ('steal', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TeamRanking',
            fields=[
                ('team_id', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('tour_id', models.CharField(max_length=70)),
                ('points', models.IntegerField(default=0)),
                ('rebound', models.IntegerField(default=0)),
                ('assist', models.IntegerField(default=0)),
                ('block', models.IntegerField(default=0)),
                ('steal', models.IntegerField(default=0)),
            ],
        ),
    ]
