# Generated by Django 4.0.3 on 2022-09-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_playerranking_teamranking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerranking',
            name='tour_id',
        ),
        migrations.RemoveField(
            model_name='playerranking',
            name='userName',
        ),
        migrations.RemoveField(
            model_name='teamranking',
            name='team_id',
        ),
        migrations.RemoveField(
            model_name='teamranking',
            name='tour_id',
        ),
        migrations.AddField(
            model_name='playerranking',
            name='player_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='playerranking',
            name='player_rank_id',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='team_name',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='team_rank_id',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
