# Generated by Django 4.0.3 on 2022-09-13 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_tournament_is_challange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='is_challange',
            new_name='is_challenge',
        ),
    ]
